[package]
name = "persistence-std"
version = "1.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Standard library for Persistence chain modules with CosmWasm support included"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backtraces = ["cosmwasm-std/backtraces", "persistence-std-derive/backtraces"]

[dependencies]
chrono = {version = "0.4.22", default-features = false}
cosmwasm-std = {version = "1.4.1", features = ["stargate"]}
persistence-std-derive = {version = "1.1.0", path = "../persistence-std-derive"}
prost = {version = "0.12.0", default-features = false, features = ["prost-derive"]}
prost-types = {version = "0.12.0", default-features = false}
schemars = "0.8.8"

# for query
serde = {version = "1.0", default-features = false, features = ["derive"]}
serde-cw-value = "0.7.0"
serde-json-wasm = "1.0.0"
